type ReasonCategory = 'IDENTITY' | 'POLICY' | 'TARGET' | 'LIMIT' | 'PRICING' | 'RESERVATION' | 'SERVICE';
type ReasonSeverity = 'BLOCKER' | 'WARNING';
const reason = (message: string, retryable: boolean, recoveryAction: string, httpStatus: number, observabilityClass: string, category: ReasonCategory, severity: ReasonSeverity) => ({ message, retryable, recoveryAction, httpStatus, observabilityClass, category, severity } as const);
const identity = (message: string, retryable = false) => reason(message, retryable, retryable ? 'RETRY' : 'PAY_FULL_PRICE', retryable ? 503 : 200, 'IDENTITY', 'IDENTITY', 'BLOCKER');
const policy = (message: string, retryable = false) => reason(message, retryable, retryable ? 'RETRY' : 'PAY_FULL_PRICE', retryable ? 503 : 200, 'POLICY', 'POLICY', 'BLOCKER');
const target = (message: string, retryable = false) => reason(message, retryable, retryable ? 'RETRY' : 'PAY_FULL_PRICE', retryable ? 503 : 200, 'TARGET', 'TARGET', 'BLOCKER');
const limit = (message: string, retryable = false) => reason(message, retryable, retryable ? 'RETRY' : 'PAY_FULL_PRICE', retryable ? 503 : 200, 'LIMIT', 'LIMIT', 'BLOCKER');
const pricing = (message: string, retryable = false) => reason(message, retryable, retryable ? 'RETRY' : 'CONFIRM_PRICE', retryable ? 503 : 200, 'PRICE', 'PRICING', 'BLOCKER');
const reservation = (message: string, retryable: boolean, recoveryAction: string, httpStatus: number) => reason(message, retryable, recoveryAction, httpStatus, 'RESERVATION', 'RESERVATION', 'BLOCKER');

export const MANAGED_SUBSCRIPTION_RUNTIME_REASON_CODES = {
  SUBSCRIPTION_NOT_FOUND: identity('Подписка не найдена.'), SUBSCRIPTION_SELECTION_REQUIRED: identity('Выберите подписку для этой услуги.'), SUBSCRIPTION_NOT_OWNED_BY_ACTOR: identity('Подписка не принадлежит текущему пользователю.'), SUBSCRIPTION_TYPE_MISMATCH: identity('Подписка не соответствует правилам услуги.'), SUBSCRIPTION_PENDING_ACTIVATION: identity('Подписка ожидает активации.'), SUBSCRIPTION_INACTIVE: identity('Подписка сейчас недоступна.'), SUBSCRIPTION_FROZEN: identity('Подписка заморожена.'), SUBSCRIPTION_EXPIRED: identity('Срок действия подписки закончился.'), SUBSCRIPTION_CANCELLED: identity('Подписка отменена.'), SUBSCRIPTION_REFUNDED: identity('Подписка возвращена.'), SUBSCRIPTION_REVOKED: identity('Подписка отозвана.'), SUBSCRIPTION_INSTANCE_STALE: identity('Данные подписки обновляются.', true), PROVIDER_IDENTITY_UNAVAILABLE: identity('Данные подписки временно недоступны.', true), PROVIDER_STATE_MISMATCH: identity('Статус подписки требует уточнения.', true),
  POLICY_UNAVAILABLE: policy('Правила подписки временно недоступны.', true), POLICY_NOT_PUBLISHED: policy('Правила подписки не опубликованы.'), POLICY_NOT_EFFECTIVE: policy('Правила подписки ещё не вступили в силу.'), POLICY_STALE: policy('Правила подписки обновляются.', true), POLICY_VERSION_MISMATCH: policy('Версия правил подписки требует обновления.', true), POLICY_DIGEST_MISMATCH: policy('Целостность правил подписки требует уточнения.', true), POLICY_MAPPING_UNVERIFIED: policy('Связь правил подписки не подтверждена.', true), POLICY_ACTION_DISABLED: policy('Эта операция отключена правилами подписки.'),
  TARGET_NOT_FOUND: target('Услуга не найдена.'), TARGET_NOT_SERVER_RESOLVED: target('Параметры услуги не подтверждены сервером.', true), TARGET_STALE: target('Данные услуги обновляются.', true), TARGET_REVISION_MISMATCH: target('Услуга изменилась. Повторите расчёт.', true), PRICE_UNAVAILABLE: target('Цена услуги временно недоступна.', true), PRICE_STALE: target('Цена услуги обновляется.', true), PRICE_REVISION_MISMATCH: target('Цена услуги изменилась. Повторите расчёт.', true), CURRENCY_UNSUPPORTED: target('Валюта услуги не поддерживается.'), EVENT_NOT_INCLUDED: target('Подписка не действует для выбранной услуги.'), PRODUCT_NOT_INCLUDED: target('Подписка не действует для выбранного продукта.'), DURATION_NOT_ALLOWED: target('Длительность услуги не поддерживается подпиской.'), STATION_NOT_ALLOWED: target('Подписка не действует для выбранной станции.'), STATION_RULE_AMBIGUOUS: target('Правило станции требует уточнения.', true), BOOKING_WINDOW_EXCEEDED: target('Услуга находится за пределами окна записи.'), BLACKOUT_DATE: target('Подписка не действует в выбранную дату.'),
  ACTIVE_SERVICES_LIMIT_REACHED: limit('Достигнут лимит активных услуг.'), ACTIVE_SERVICES_LIMIT_UNAVAILABLE: limit('Лимит активных услуг временно недоступен.', true), DAILY_LIMIT_REACHED: limit('Дневной лимит подписки исчерпан.'), WEEKLY_LIMIT_REACHED: limit('Недельный лимит подписки исчерпан.'), MONTHLY_LIMIT_REACHED: limit('Месячный лимит подписки исчерпан.'), FUTURE_BOOKINGS_LIMIT_REACHED: limit('Достигнут лимит будущих записей.'), MIN_INTERVAL_NOT_MET: limit('Минимальный интервал между услугами не соблюдён.'), UNITS_EXHAUSTED: limit('Недостаточно доступных посещений.'), USAGE_SNAPSHOT_STALE: limit('Данные использования обновляются.', true), USAGE_SNAPSHOT_INVALID: limit('Данные использования требуют уточнения.', true),
  BENEFIT_NOT_APPLICABLE: pricing('Подписка не применяется к выбранной услуге.'), DISCOUNT_DISABLED: pricing('Скидка по подписке отключена.'), PRICE_CALCULATION_INVALID: pricing('Цена услуги требует уточнения.', true), PRICE_CHANGED: pricing('Цена изменилась; подтвердите её ещё раз.'), PRICE_CONFIRMATION_REQUIRED: pricing('Подтвердите обновлённую цену.'),
  RESERVATION_CONFLICT: reservation('Право на использование изменилось. Повторите расчёт.', true, 'REQUOTE', 409), RESERVATION_EXPIRED: reservation('Срок предварительного расчёта истёк.', true, 'REQUOTE', 409), RESERVATION_NOT_OWNED_BY_ACTOR: reservation('Операция недоступна текущему пользователю.', false, 'NONE', 403), IDEMPOTENCY_CONFLICT: reservation('Запрос конфликтует с предыдущей операцией.', false, 'NEW_IDEMPOTENCY_KEY', 409), PROVIDER_UNAVAILABLE: reservation('Внешняя система временно недоступна.', true, 'RETRY', 503), PROVIDER_REJECTED: reservation('Операция отклонена внешней системой.', false, 'PAY_FULL_PRICE', 409), PROVIDER_TIMEOUT_AFTER_ACCEPT: reservation('Статус операции уточняется. Повторно не отправляйте запрос.', false, 'WAIT_FOR_RECONCILIATION', 202), PROVIDER_READBACK_MISMATCH: reservation('Статус операции требует уточнения.', false, 'WAIT_FOR_RECONCILIATION', 202), RECONCILIATION_REQUIRED: reservation('Статус операции уточняется. Повторно не отправляйте запрос.', false, 'WAIT_FOR_RECONCILIATION', 202), CROSS_TENANT_REJECTED: reservation('Запрос не может быть обработан.', false, 'NONE', 403), LEGACY_FLOW_NOT_MANAGED: reservation('Эта операция пока не поддерживается управляемой подпиской.', false, 'USE_LEGACY_FLOW', 409),
  SERVICE_UNAVAILABLE: reason('Услуга сейчас недоступна.', false, 'NONE', 409, 'SERVICE', 'SERVICE', 'BLOCKER')
} as const;
export type ManagedSubscriptionRuntimeReasonCode = keyof typeof MANAGED_SUBSCRIPTION_RUNTIME_REASON_CODES;
export type ManagedSubscriptionRuntimeReasonMetadata = (typeof MANAGED_SUBSCRIPTION_RUNTIME_REASON_CODES)[ManagedSubscriptionRuntimeReasonCode];
